@extends('layouts.app')
@section('title','Lead Status')
@section('content')
@include('crm._page_header', ['title' => 'Add Lead Status', 'subtitle' => 'Dynamic status with admission/final flags'])
<div class="row"><div class="col-lg-4"><div class="card"><div class="card-header"><h4 class="card-title mb-0">Add Status</h4></div><div class="card-body"><form method="POST" action="{{ route('settings.lead-statuses.store') }}">@csrf
<div class="mb-2"><label>Name</label><input name="name" class="form-control" required></div><div class="mb-2"><label>Color</label><input name="color" class="form-control" value="primary"></div><div class="mb-2"><label>Sort Order</label><input type="number" name="sort_order" class="form-control" value="0"></div>
@foreach(['is_default'=>'Default Status','is_final'=>'Final Status','is_admission'=>'Admission Status','is_active'=>'Active'] as $field=>$label)<div class="form-check"><input class="form-check-input" type="checkbox" name="{{ $field }}" value="1" {{ $field=='is_active'?'checked':'' }}><label class="form-check-label">{{ $label }}</label></div>@endforeach
<button class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="col-lg-8"><div class="card"><div class="card-header"><h4 class="card-title mb-0">Status List</h4></div><div class="card-body table-responsive"><table class="table table-hover"><thead class="table-light"><tr><th>Name</th><th>Color</th><th>Order</th><th>Flags</th><th>Action</th></tr></thead><tbody>@foreach($items as $item)<tr><form method="POST" action="{{ route('settings.lead-statuses.update', $item) }}">@csrf @method('PUT')<td><input name="name" class="form-control form-control-sm" value="{{ $item->name }}"></td><td><input name="color" class="form-control form-control-sm" value="{{ $item->color }}"></td><td><input type="number" name="sort_order" class="form-control form-control-sm" value="{{ $item->sort_order }}"></td><td>@foreach(['is_default'=>'Default','is_final'=>'Final','is_admission'=>'Admission','is_active'=>'Active'] as $field=>$label)<label class="me-2"><input type="checkbox" name="{{ $field }}" value="1" @checked($item->{$field})> {{ $label }}</label>@endforeach</td><td><button class="btn btn-sm btn-primary">Update</button></form><form method="POST" action="{{ route('settings.lead-statuses.destroy', $item) }}" class="d-inline" onsubmit="return confirm('Delete?')">@csrf @method('DELETE')<button class="btn btn-sm btn-light border text-danger">Delete</button></form></td></tr>@endforeach</tbody></table>{{ $items->links() }}</div></div></div></div>
@endsection
